name: Hello World Pipeline
on:
  push:
    branches:
      - main
env:
  my_name: Welcome to

jobs:
  machine:
    runs-on: ubuntu-latest
    env:
      behafname: behaf of meharwan

    steps:
    - name: Print Hello World
      run: echo "$my_name $behafname"
