name: Terraform Infra Workflow
on:
 push:
   branches:
     - main

jobs:
  terraforminstallJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: terraform instalation
        uses: hashicorp/setup-terraform@v2.0.3

      - name: check terraform version
        run: terraform --version

      - name: terraform init step
        run: terraform init
        working-directory: envirionments/dev

       - name: terraform plan task
         run: terraform plan
         working-directory: envirionments/dev
         
    



        





    

  
  
  
  
     



    
