name: Terraform Infra Workflow
on:
 push:
   branches:
     - main
     
permissions:
  id-token: write
  contents: read

env:
  

jobs:
  terraforminstallJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: terraform instalation
        uses: hashicorp/setup-terraform@v2.0.3

      - name: check terraform version
        run: terraform --version

      - name: terraform init step
        run: terraform init
        working-directory: envirionments/dev

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
         
      - name: az account show
        run: az account show

      - name: terraform plan task
        run: terraform plan
        working-directory: envirionments/dev
         
    



        





    

  
  
  
  
     



    
