name: Terraform Infra Workflow
on:
 push:
   branches:
     - main
env:
  haalchaal: Bhadhiya hu
  
jobs:
  scriptJob:
    runs-on: ubuntu-latest

    steps:
      - name: running a script
        run: echo "hello Dosto $haalchaal"
  
  
     



    
