name: Terraform Workflow

on:
  workflow_dispatch:
jobs:
  installjob:
    runs-on: ubuntu-latest

    steps:
      
       

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout Repository
        uses: actions/checkout@v4   

      - name: Verify Terraform Installation
        run: terraform version
        working-directory: environments/dev

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: environments/dev
