name: santanbhai
on:
  workflow_dispatch:
env:
  Greetings: Namskaar
  
jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
    -  name: runscript
       run: echo "Hell $Greetings Bhai Jaan"
  
  
